p, g = map(int, input("Enter prime no.(p) and primitive root(g): ").strip().split())
xa = int(input("\nSelect private key for Alice: Xa = "))
xb = int(input("Select private key for Bob: Xb = "))
ya = pow(g, xa, p)
print("\nAlice's public key is: Ya = ", ya)
yb = pow(g, xb, p)
print("Bob's public key is: Yb = ", yb)
print("\nExchange of public key in plain text...")
print("\nShared private key (Alice) k = ", pow(yb, xa, p))
print("Shared private key (Bob) k = ",pow(ya, xb, p))